### ISSUE TITLE
Poster review

### ISSUE THREAD

**Issue by blegat** [blegat/SumOfSquaresSlides#2]
Let me know if you have any feedback on the poster, I will present it at https://www.mis.mpg.de/calendar/conferences/2018/nc2018.html next week.
@chriscoey Is it too early to talk about Alfonso.jl ? I have made a brief mention of it in the slides because it give an example in which the SOS constraints will not be bridged into PSD constraint but let me know what you think of it :)

**Comment by chriscoey** [comment]
I'm in LA without a laptop rn but I'll try to take a look on my phone. 

Yes it's ok to mention that we should have a SOS ipm without SDP soon, but it probably won't be called Alfonso when I release it.

**Comment by chriscoey** [comment]
I can't compile but if you send a PDF or put it on here I can take a look

**Comment by blegat** [comment]
Done on 7ca64098d74f5aa0c57a45658eefe6221f0146dd
Note that their is currently a weird issue so it's on page 2 and page 1 is empty :-P

**Comment by chriscoey** [comment]
Looks good. BTW the SOS IPM does weighted SOS (WSOS) if desired. Maybe WSOS is worth mentioning.

**Comment by blegat** [comment]
I have just pushed a first printable candidate. Last chance for comments, I print it tomorrow morning :)

**Comment by blegat** [comment]
Printed :)
